# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'yourNYTimes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for yourNYTimes
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'SwiftyJSON'

end
